version: '3.8'

services:
  evolution:
    image: atendai/evolution-api:v2.3.7
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVER_URL=http://localhost:8080
      - AUTHENTICATION_API_KEY=qbombom_evolution_key
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - DEL_INSTANCE=false
      - LANGUAGE=pt-BR
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://marquin:Senha123!@172.18.0.1:5432/evolution_api
      - DATABASE_URL=postgresql://marquin:Senha123!@172.18.0.1:5432/evolution_api
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_api
      - CACHE_REDIS_ENABLED=false
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1023204200
    volumes:
      - evolution_data:/evolution/instances

volumes:
  evolution_data:
